---
- name: Inserisci chiave gpg per syncthing
  apt_key:
    id: 00654A3E
    url: https://syncthing.net/release-key.txt
    state: present

- name :
  apt_repository:
    repo: deb http://apt.syncthing.net/ syncthing release
    state: present

- name: create "home" folder
  become: true
  file: path={{syncthing_home}} recurse=yes state=directory owner={{syncthing_user}} group={{syncthing_user}} mode=755

- name: set ownership
  become: true
  file: path={{syncthing_home}} recurse=yes owner={{syncthing_user}} group={{syncthing_user}}

- name: installa pacchetti
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - syncthing

- name: Creazione Service
  become: true
  template: src=syncthing.service dest=/etc/systemd/system/syncthing.service mode=755
  register: systemd_conf
  notify: reload systemd

- meta: flush_handlers

- name: Servizio Syncthing attivo
  service: name=syncthing state=started enabled=yes

- name: check syncthing version
  become: true
  become_user: "{{ syncthing_user }}"
  shell: "/usr/bin/syncthing --version | awk '{ print $2 }' | cut -c 2-"
  changed_when: false
  ignore_errors: true
  register: version

- name: waiting for configfile (takes some time)
  become: true
  become_user: "{{ syncthing_user }}"
  wait_for: path={{syncthing_home}}/config.xml

- name: config.xml | webinterface address
  become: true
  become_user: "{{ syncthing_user }}"
  lineinfile: dest={{syncthing_home}}/config.xml
              regexp="<address>[^<]+</address>"
              line="        <address>{{syncthing_address}}</address>"
  notify: restart syncthing

- name: config.xml | listen address
  become: true
  become_user: "{{ syncthing_user }}"
  lineinfile: dest={{syncthing_home}}/config.xml
              regexp="<listenAddress>[^<]+</listenAddress>"
              line="        <listenAddress>{{syncthing_listen}}</listenAddress>"
  notify: restart syncthing

- name: config.xml | localAnnounceEnabled
  become: true
  become_user: "{{ syncthing_user }}"
  lineinfile: dest={{syncthing_home}}/config.xml
              regexp="<localAnnounceEnabled>[^<]+</localAnnounceEnabled>"
              line="        <localAnnounceEnabled>{{syncthing_localannounce|lower}}</localAnnounceEnabled>"
  notify: restart syncthing

- name: config.xml | globalAnnounceEnabled
  become: true
  become_user: "{{ syncthing_user }}"
  lineinfile: dest={{syncthing_home}}/config.xml
              regexp="<globalAnnounceEnabled>[^<]+</globalAnnounceEnabled>"
              line="        <globalAnnounceEnabled>{{syncthing_globalannounce|lower}}</globalAnnounceEnabled>"
  notify: restart syncthing

- name: config.xml | upnpEnabled
  become: true
  become_user: "{{ syncthing_user }}"
  lineinfile: dest={{syncthing_home}}/config.xml
              regexp="<upnpEnabled>[^<]+</upnpEnabled>"
              line="        <upnpEnabled>{{syncthing_upnp|lower}}</upnpEnabled>"
  notify: restart syncthing

